# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQq9acikTHQ26j-XLkp5OadylQCyRjdN
"""

#1WAP to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (incuded both).

x=1500
while x>=1500 and x<=2700:
  if x%7==0 and x%5==0:
    print(x, end=",")
  x+=1

#2WAP to convert temperatures to and from celsius and fahrenheit.

x= int(input("Enter the choice for unit you are entering (1 for celsius and 2 for fahrenheit): "))
y= int(input("Enter the temperature: "))

if x==1:
    f=y*(9/5)+32
    print("The temperature in fahrenheit is: "+str(f))
elif x==2:
  c=(y-32)*(5/9)
  print("The temperature in celsius is: "+str(c))

"""#3write a program to guess a number between 1 to 9.

"""

while True:
  x= int(input("Guess a number (only between 1 to 9): "))
  if x>=1 and x<=9:
    if x==7:
      print("Well guessed!")
      break
    else:
      print("Try again!")
  else:
    print("Wrong input!")

"""4 Write a program to construct the following pattern using a nested for loop."""

i=1

while i<=5:
  j=1
  while j<=i:
    print("*",end="")
    j+=1
  print()
  i+=1
i=1
while i<=4:
  j=1
  while j<=5-i:
    print("*", end="")
    j+=1
  i+=1
  print()

"""5 Write a program that accepts a word from the user and reverse it."""

x= input("Enter a word: ")
i=0
while i<=len(x)-1:
  j=len(x)-1-i
  print(x[j],end="")
  i+=1

"""6 Write a program to count the number of even and odd numbers from a series of numbers.

"""

s = [1,2,3,4,5,6,7,8,9]
i=0
e=0
o=0
while i<=len(s)-1:
  if (s[i]%2==0):
    e+=1
  else:
    o+=1
  i+=1
print("The number of even numbers is "+str(e))
print("The number of odd numbers is "+str(o))

"""7 Write a python program that prints each item and its corresponding type from the following list."""

sample = [1452,11.23,1+2j,True,'w3resource',(0,-1),[5,12],{"class":"V", "Section":"A"}]

i=0
while i<=len(sample)-1:
  print(type(sample[i]))
  i+=1

"""8 Write a program that prints all the numbers from 0 to 6 except 3 and 6."""

i=0
while i<=6:
  if i==3 or i==6:
    i+=1
  else:
    print(i)
    i+=1

"""9 Write a program to get the Fibonacci series between 0 to 50."""

a=0
b=1
c=a+b
print(a)
print(b)
while c<=50:
  print(c)
  a=b
  b=c
  c=a+b

"""10 Write a python program which iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz"."""

i=1
while i<=50:
  if (i%3==0):
    print("Fizz")
  elif (i%5==0):
    print("Buzz")
  elif (i%3==0 and i%5==0):
    print("FizzBuzz")
  else:
    print(i)
  i+=1

"""11 Write a program which takes two digits m (row) and n (column) as input and generates a two-dimensional array. The element value in the i-th row and j-th column of the array should be i*j."""

m = int(input("Enter the number of rows: "))
n = int(input("Enter the number of columns: "))

i=0
j=0
while i<=m: